name: Notify Portfolio to Rebuild

on:
  push:
    branches: [main]

jobs:
  ping-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Portfolio Rebuild
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PORTFOLIO_TOKEN }}" \
            https://api.github.com/repos/ilhamjkid/ilhamjkid.github.io/dispatches \
            -d '{"event_type": "project-updated"}'
